name: "Dev Workflow"
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  test:
    name: Unit-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Maven Package and Test
        run: |
          cd backend
          mvn -B clean
          mvn -B test --file pom.xml
